export const Props = ["Lorem ipsum dolor sit amet, consectetur adipiscing elit. Quisque quis finibus mi, vel luctus neque. Suspendisse potenti. Mauris sed metus aliquet nisi mattis tempus. Aenean mollis fringilla placerat. Nam sit amet venenatis urna, a consectetur lectus. Donec eu porttitor neque. Aliquam erat volutpat. Cras congue lacus ex, vitae aliquam nibh ultricies et. In ac leo eu dolor lobortis fringilla. Donec ornare varius varius. Sed a sollicitudin lacus, a porttitor diam."
,
"Proin vel justo a nisl viverra venenatis a eget felis. Mauris blandit sodales rutrum. Nulla id arcu pellentesque, sollicitudin arcu imperdiet, suscipit orci. Etiam efficitur urna in quam placerat, ut tempus ante laoreet. Nunc a felis at odio pretium porttitor. Quisque volutpat, nulla hendrerit porttitor commodo, risus risus luctus eros, nec aliquet urna nisi vitae ante. Integer congue egestas porta. Fusce imperdiet orci in quam congue, vitae bibendum ipsum aliquam. Duis a diam venenatis, faucibus tellus sed, venenatis mauris."
,
"Praesent facilisis nisl sit amet justo lobortis, ac venenatis leo tristique. Sed vitae nisi vulputate justo blandit laoreet eu aliquet massa. Mauris dignissim, nisl at dictum interdum, eros felis congue arcu, aliquet cursus enim leo eu diam. Nam sed pulvinar urna. Quisque sed pulvinar urna, posuere egestas tellus. Sed imperdiet, elit non dapibus lobortis, ipsum turpis malesuada turpis, vitae semper tortor nunc auctor mi. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Ut viverra, velit vel laoreet dignissim, ante diam vulputate mi, a molestie lectus quam a nulla. Proin at sollicitudin nibh. In et ornare enim, ac imperdiet mi. Vestibulum feugiat nulla et dolor fringilla, at eleifend nulla consequat. Nullam sodales purus ut mi ornare, dapibus viverra diam venenatis. Maecenas auctor ante maximus, euismod metus vel, pulvinar lacus. Sed sit amet lacus magna. Duis vitae quam ut nunc tincidunt mollis nec eu erat."
,
"Integer sit amet lobortis lorem, a sodales nulla. Etiam porta, orci vel cursus interdum, tortor diam vestibulum erat, eu sagittis eros lectus vitae nisi. Praesent vel lectus nisi. Donec luctus dolor purus, nec sodales neque bibendum id. Fusce in malesuada massa, et pulvinar nisi. Pellentesque vel sapien urna. Pellentesque ac imperdiet sapien. Fusce fringilla fermentum enim quis gravida. Proin dolor nibh, suscipit eget risus non, tempus elementum mi. Sed tincidunt arcu vel nunc lobortis, ut scelerisque odio iaculis. In hac habitasse platea dictumst. In vulputate nisl quis eleifend mattis."
,
"Fusce tempus dictum dolor et facilisis. Duis pretium, orci sed iaculis tincidunt, massa velit volutpat neque, at ullamcorper lectus risus mollis mauris. Nullam sodales dui orci, id ullamcorper magna tincidunt at. Aenean velit felis, tincidunt ut tempor vitae, mollis ac sem. Cras nec vulputate metus, eu tincidunt leo. Nullam maximus erat eu diam mollis semper. Vestibulum nec turpis ac ex blandit aliquet non id justo. Quisque nec consectetur enim. Ut id rhoncus mauris. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae; Sed at mi imperdiet neque maximus ornare. Vestibulum varius quam eu tellus rutrum gravida."
]
